#! /usr/bin/env bash

# TODO: READ INSTANCE_NAME FROM CONFIG.
INSTANCE_NAME='my-ghost-blog'
TAG="${INSTANCE_NAME}:${INSTANCE_TAG}"

if [[ "${ENV_TAG}" != 'production' ]]; then
  # TODO: VERIFY THAT ENV_TAG HAS A VALID VALUE: production/development
  ENV_TAG='development'
  INSTANCE_TAG='development'
else 
  ENV_TAG='production'
  INSTANCE_TAG='latest'
fi

DOCKER_TEMPLATE="Dockerfile.${ENV_TAG}"

cat "${DOCKER_TEMPLATE}" > Dockerfile
docker build -t $TAG .
rm Dockerfile 

docker build -t $TAG .